CREATE TABLE users (
    id              		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           		TEXT NOT NULL UNIQUE,
    password_hash  			TEXT NOT NULL,
    full_name       		TEXT NOT NULL,
    phone           		CHAR(10),
    dob             		DATE,
	address					TEXT,
    avatar_url      		TEXT,
    role            		TEXT NOT NULL DEFAULT 'CANDIDATE',
    status          		TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at      		TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      		TIMESTAMP NOT NULL DEFAULT NOW(),
	email_verified  		BOOLEAN NOT NULL DEFAULT FALSE,
	verification_code 		TEXT,
	verification_expiry 	TIMESTAMP,
	ntd_search 				BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE users
ADD COLUMN is_online BOOLEAN DEFAULT FALSE,
ADD COLUMN last_online_at TIMESTAMP;

CREATE TABLE companies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
	location		TEXT NOT NULL,
	logo			TEXT,
    address         TEXT NOT NULL,
    website         TEXT,
    tax_code        TEXT,
	email			TEXT,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE companies ADD COLUMN search_tsv tsvector;

CREATE OR REPLACE FUNCTION companies_search_trigger() RETURNS trigger AS $$
BEGIN
  NEW.search_tsv :=
    to_tsvector('english', coalesce(NEW.name, '')) ||
    to_tsvector('simple', coalesce(NEW.name, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER companies_tsvector_update
BEFORE INSERT OR UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION companies_search_trigger();

CREATE INDEX companies_search_tsv_idx ON companies USING gin(search_tsv);

ALTER TABLE companies
ADD COLUMN is_online BOOLEAN DEFAULT FALSE,
ADD COLUMN last_online_at TIMESTAMP;

CREATE TABLE company_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	position		TEXT,
    is_admin        BOOLEAN NOT NULL DEFAULT FALSE,
    status          TEXT NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (company_id, user_id)
);

CREATE TABLE hr_view_candidate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hr_id      		BIGINT NOT NULL REFERENCES company_members(id) ON DELETE CASCADE,
    candidate_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE cvs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    file_url        TEXT NOT NULL,
    level           TEXT NOT NULL, 
    experience      TEXT NOT NULL,     
    job_title       TEXT,               
    content         TEXT,                    
    content_tsv     tsvector, 
    is_public       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cvs_content_tsv ON cvs USING GIN (content_tsv);

CREATE FUNCTION cvs_tsvector_update() RETURNS trigger AS $$
BEGIN
  NEW.content_tsv :=
    to_tsvector('english', coalesce(NEW.content, '')) || 
	to_tsvector('simple', coalesce(NEW.content, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cvs_tsvector_update
BEFORE INSERT OR UPDATE OF content
ON cvs
FOR EACH ROW
EXECUTE FUNCTION cvs_tsvector_update();

CREATE TABLE jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
	member_id     	BIGINT NOT NULL REFERENCES company_members(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    location        TEXT NOT NULL,
	address 		TEXT NOT NULL,
    description     TEXT NOT NULL,
	requirement		TEXT NOT NULL,
	benefit			TEXT NOT NULL,
	working_time	TEXT NOT NULL,
    job_type        TEXT NOT NULL,
	level			TEXT NOT NULL,
	contract_type	TEXT NOT NULL,
	salary			TEXT NOT NULL,
	experience		TEXT NOT NULL,
	quantity		INT NOT NULL,
	deadline		DATE NOT NULL,
    status          TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
	search_tsv		tsvector
);

CREATE OR REPLACE FUNCTION jobs_search_trigger() RETURNS trigger AS $$
BEGIN
  NEW.search_tsv :=
    to_tsvector('english', coalesce(NEW.title, '')) ||
    to_tsvector('simple', coalesce(NEW.title, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER jobs_tsvector_update
BEFORE INSERT OR UPDATE ON jobs
FOR EACH ROW EXECUTE FUNCTION jobs_search_trigger();

CREATE INDEX jobs_search_tsv_idx ON jobs USING gin(search_tsv);

CREATE TABLE applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    candidate_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	file_name 		TEXT NOT NULL,
    cv_url          TEXT NOT NULL,
    cover_letter    TEXT,
    status          TEXT NOT NULL DEFAULT 'APPLIED',
    applied_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (job_id, candidate_id)
);

CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_from       BIGINT REFERENCES users(id) ON DELETE CASCADE,
    user_to         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	title			TEXT NOT NULL,
    message         TEXT NOT NULL,
	url				TEXT,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE skills (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL UNIQUE
);

CREATE TABLE company_skills (
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    skill_id    	BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (company_id, skill_id)
);

CREATE TABLE job_skills (
    job_id      BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    skill_id    BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, skill_id)
);

CREATE TABLE cv_skills (
    cv_id       BIGINT NOT NULL REFERENCES cvs(id) ON DELETE CASCADE,
    skill_id    BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (cv_id, skill_id)
);

CREATE TABLE saved_jobs (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id 	BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id 			BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    saved_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(candidate_id, job_id)
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    candidate_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	last_message 	TEXT,
	last_message_at TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (company_id, candidate_id)
);

ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS company_last_read_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS candidate_last_read_at TIMESTAMP;

CREATE INDEX idx_conversations_candidate_last_read ON conversations(candidate_id, last_message_at, candidate_last_read_at);
CREATE INDEX idx_conversations_company_last_read ON conversations(company_id, last_message_at, company_last_read_at);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at ON messages(conversation_id, created_at DESC);

ALTER TABLE messages ADD COLUMN IF NOT EXISTS seen_at TIMESTAMP;
CREATE INDEX idx_messages_conversation_sender_seen ON messages (conversation_id, sender_id, seen_at, created_at);


DO $$
DECLARE
    rec RECORD;
    tbl_name text;
    col_name text;
    seq_name text;
    last_id bigint;
BEGIN
    -- Lấy tất cả các sequence trong DB (thường gắn với SERIAL/IDENTITY)
    FOR rec IN
        SELECT
            n.nspname AS schema_name,
            c.relname AS seq_name,
            t.relname AS tbl_name,
            a.attname AS col_name
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_depend d ON d.objid = c.oid
        JOIN pg_class t ON d.refobjid = t.oid
        JOIN pg_attribute a ON d.refobjid = a.attrelid AND d.refobjsubid = a.attnum
        WHERE c.relkind = 'S'
    LOOP
        seq_name := rec.schema_name || '.' || rec.seq_name;
        tbl_name := rec.schema_name || '.' || rec.tbl_name;
        col_name := rec.col_name;

        -- Lấy MAX(id) của bảng
        EXECUTE format('SELECT COALESCE(MAX(%I), 1) FROM %s', col_name, tbl_name) INTO last_id;

        -- Reset sequence về đúng giá trị MAX(id)
        EXECUTE format('SELECT setval(%L, %s, false)', seq_name, last_id);
    END LOOP;
END$$;

INSERT INTO skills (name) VALUES
('Java'), ('Spring Boot'), ('PostgreSQL'),
('React'), ('Angular'), ('TypeScript'),
('Docker'), ('AWS'), ('Kubernetes'),
('JavaScript'),
('Python'),
('C#'),
('C++'),
('C'),
('Go'),
('Rust'),
('Kotlin'),
('Swift'),
('PHP'),
('Ruby'),
('Dart'),
('Scala'),
('HTML'),
('CSS'),
('Sass'),
('Tailwind CSS'),
('Bootstrap'),
('Next.js'),
('Vue.js'),
('Nuxt.js'),
('jQuery'),
('Spring Framework'),
('.NET Core'),
('ASP.NET'),
('Express.js'),
('NestJS'),
('Django'),
('Flask'),
('FastAPI'),
('Ruby on Rails'),
('Laravel'),
('Symfony'),
('Golang Gin'),
('MySQL'),
('SQL Server'),
('SQLite'),
('Oracle'),
('MongoDB'),
('Redis'),
('Elasticsearch'),
('Firebase'),
('Cassandra'),
('Jenkins'),
('GitLab CI/CD'),
('GitHub Actions'),
('Google Cloud Platform'),
('Microsoft Azure'),
('Terraform'),
('Ansible'),
('Git'),
('Linux'),
('Bash Scripting'),
('REST API'),
('GraphQL'),
('gRPC'),
('Microservices'),
('Event-Driven Architecture'),
('Clean Architecture'),
('Design Patterns'),
('Pandas'),
('NumPy'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('Machine Learning'),
('Deep Learning'),
('Data Analysis'),
('Data Visualization'),
('MLOps'),
('Android'),
('iOS'),
('Flutter'),
('React Native'),
('SwiftUI'),
('Jetpack Compose'),
('JUnit'),
('Mockito'),
('Selenium'),
('Cypress'),
('Playwright'),
('Jest'),
('Mocha'),
('Chai'),
('Postman'),
('OAuth 2.0'),
('OpenID Connect'),
('JWT'),
('Penetration Testing'),
('OWASP Top 10'),
('HTTPS'),
('SSO'),
('Agile'),
('Scrum'),
('Kanban'),
('Jira'),
('Confluence'),
('CI/CD'),
('Unit Testing'),
('Integration Testing'),
('Code Review'),
('Refactoring');

INSERT INTO users (email, password_hash, full_name, phone, dob, address, avatar_url, role, status, email_verified)
VALUES 
('admin@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Admin User', NULL, NULL, NULL, NULL, 'ADMIN', 'ACTIVE', TRUE),
('candidate1@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Nguyen Van A', '0912345678', '2000-05-15', 'Hà Nội', NULL, 'CANDIDATE', 'ACTIVE', FALSE),
('candidate2@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Nguyen Van B', '0912345678', '2000-05-15', 'Hà Nội', NULL, 'CANDIDATE', 'ACTIVE', FALSE),
('candidate3@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Nguyen Van C', '0912345678', '2000-05-15', 'Hà Nội', NULL, 'CANDIDATE', 'ACTIVE', FALSE),
('candidate4@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Nguyen Van D', '0912345678', '2000-05-15', 'Hà Nội', NULL, 'CANDIDATE', 'ACTIVE', FALSE),
('hr1@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Tran Thi B', '0987654321', '1995-08-20', 'Hồ Chí Minh', NULL, 'HR', 'ACTIVE', TRUE),
('hr2@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Tran Thi C', '0987654321', '1995-08-20', 'Hà Nội', NULL, 'HR', 'ACTIVE', TRUE),
('hr3@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Tran Thi D', '0987654321', '1995-08-20', 'Hồ Chí Minh', NULL, 'HR', 'ACTIVE', TRUE),
('hr4@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Tran Thi E', '0987654321', '1995-08-20', 'Hà Nội', NULL, 'HR', 'ACTIVE', TRUE),
('hr5@example.com', '$2a$10$dSle55eIgRfnJdmQ1KiMdOqjklkHZgOf3ZEvnbxHYSUpmqMIs.3ne', 'Tran Thi F', '0987654321', '1995-08-20', 'Hồ Chí Minh', NULL, 'HR', 'ACTIVE', TRUE);
INSERT INTO companies (name, location, logo, address, website, tax_code, email, description, status)
VALUES 
('Tech Startup VN', 'HANOI', NULL, '123 Hoang Quoc Viet, Hà Nội', 'https://techstartup.vn', '123456789', 'hr@techstartup.vn', 'Công ty công nghệ khởi nghiệp', 'APPROVED'),
('Ecom Corp', 'HOCHIMINH', NULL, '456 Le Loi, TP.HCM', 'https://ecomcorp.com', '987654321', 'hr@ecomcorp.com', 'Doanh nghiệp thương mại điện tử', 'PENDING');
-- HR thuộc công ty Tech Startup VN
INSERT INTO company_members (company_id, user_id, position, is_admin, status)
VALUES 
(1, 6, 'HR Manager', TRUE, 'APPROVED');
INSERT INTO company_members (company_id, user_id, position, is_admin, status)
VALUES 
(2, 7, 'HR Executive', TRUE, 'APPROVED');
INSERT INTO jobs (company_id, member_id, title, location, address, description, requirement, benefit, working_time, job_type, level, contract_type, salary, experience, quantity, deadline, status)
VALUES 
(1, 1, 'React Frontend Developer', 'HANOI', '123 Hoang Quoc Viet, Hà Nội', 
 'Phát triển giao diện web bằng React', 
 'Thành thạo React, Redux, TypeScript', 
 'Môi trường startup, cơ hội thăng tiến', 
 'Full-time, 8h-17h', 
 'IN_OFFICE', 'JUNIOR', 'FULL_TIME', 'TU_15_DEN_20_TRIEU', 'MOT_NAM', 2, '2025-12-31', 'ACTIVE'),

(2, 2, 'Backend Java Developer', 'HOCHIMINH', '456 Le Loi, TP.HCM', 
 'Phát triển hệ thống backend bằng Java/Spring Boot', 
 'Kinh nghiệm 1-2 năm với Spring Boot, SQL', 
 'Lương thưởng hấp dẫn, bảo hiểm đầy đủ', 
 'Full-time, 9h-18h', 
 'HYBRID', 'MIDDLE', 'FULL_TIME', 'TU_20_DEN_25_TRIEU', 'HAI_NAM', 3, '2025-12-20', 'ACTIVE');

